set -x

train_files="['/scratch/nishang/data/template_orz_math_57k/train.parquet', '/scratch/nishang/data/template_code_data/train.parquet']"
test_files="['/scratch/nishang/data/template_aime2024/test.parquet']"

PYTORCH_HIP_ALLOC_CONF=expandable_segments:True RAY_EXPERIMENTAL_NOSET_ROCR_VISIBLE_DEVICES=0 NCCL_TIMEOUT=1800 python3 -m verl.trainer.main_ppo \
    data.train_files="$train_files" \
    data.val_files="$test_files" \
    data.train_batch_size=128 \
    data.val_batch_size=1024 \
    data.max_prompt_length=2048 \
    data.max_response_length=8192 \
    +data.chat_template=qwen_orz_code_math \
    data.filter_overlong_prompts=True \
    actor_rollout_ref.model.path=/scratch/nishang/Qwen2.5-32B-Instruct \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.0057 \
    actor_rollout_ref.actor.kl_loss_coef=0.0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=8192 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.actor.clip_ratio_low=0.2 \
    actor_rollout_ref.actor.clip_ratio_high=0.28 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.max_num_batched_tokens=10240 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.n=64 \
    actor_rollout_ref.rollout.temperature=1 \
    actor_rollout_ref.rollout.swap_space=56 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    reward_model.reward_manager=server \
    +reward_model.chat_template=qwen_orz_code_math \
    reward_model.overlong_buffer.enable=True \
    reward_model.overlong_buffer.len=4096 \
    reward_model.overlong_buffer.penalty_factor=1.0 \
    algorithm.kl_ctrl.kl_coef=0.0 \
    algorithm.adv_estimator=grpo \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    +trainer.val_before_train=False \
    +trainer.conda_env=rstar \
    trainer.project_name='verl-orz-math-code' \
    trainer.experiment_name='Qwen2.5-32B-Instruct-math-code-GRPO-orz-align-template-dapo' \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=4 \
    trainer.save_freq=10 \
    trainer.test_freq=-1 \
    trainer.default_local_dir=/scratch/nishang/verl_checkpoint/verl-orz-math-code/Qwen2.5-32B-Instruct-math-code-GRPO-orz-align-template-dapo \
    trainer.remove_previous_ckpt_in_save=True \
    trainer.total_epochs=20 $@ 2>&1 | tee Qwen2.5-32B-Instruct-math-code-GRPO-orz-align-template-dapo.log
