set -x

train_files="['/scratch/nishang/data/merged_data_deepscaler_openr1_130k/train.parquet']"
test_files="['/scratch/nishang/data/aime2024/test.parquet']"

PYTORCH_HIP_ALLOC_CONF=expandable_segments:True RAY_EXPERIMENTAL_NOSET_ROCR_VISIBLE_DEVICES=0 python3 -m verl.trainer.main_ppo \
    data.train_files="$train_files" \
    data.val_files="$test_files" \
    data.train_batch_size=1024 \
    data.val_batch_size=1024 \
    data.max_prompt_length=1024 \
    data.max_response_length=2048 \
    +data.chat_template=deepseek_zero_plus_qwen_2_5_math \
    actor_rollout_ref.model.path=/scratch/nishang/Qwen2.5-32B \
    actor_rollout_ref.actor.optim.lr=5e-7 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.0001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=256 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.rollout.temperature=0.6 \
    actor_rollout_ref.rollout.swap_space=4 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    reward_model.reward_manager=prime \
    +reward_model.chat_template=deepseek_zero_plus_qwen_2_5_math \
    algorithm.kl_ctrl.kl_coef=0.0001 \
    algorithm.adv_estimator=grpo \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    +trainer.val_before_train=False \
    trainer.project_name='verl_Qwen2.5-32B_GRPO' \
    trainer.experiment_name='Qwen2.5-32B-math-mix1-GRPO' \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=2 \
    trainer.save_freq=20 \
    trainer.test_freq=-1 \
    trainer.default_local_dir=/scratch/nishang/verl_checkpoint/verl_Qwen2.5-32B_GRPO/Qwen2.5-32B-math-mix1-GRPO \
    trainer.remove_previous_ckpt_in_save=True \
    trainer.total_epochs=20 $@ 2>&1 | tee Qwen2.5-32B-math-mix1-GRPO.log
